apiVersion: v1
kind: Service
metadata:
  name: gemini-voice-backend
  namespace: gemini-voice-chat
spec:
  selector:
    app: gemini-voice-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP