apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-voice-frontend
  namespace: gemini-voice-chat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gemini-voice-frontend
  template:
    metadata:
      labels:
        app: gemini-voice-frontend
    spec:
      containers:
        - name: gemini-voice-frontend
          image: your-docker-registry/gemini-voice-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: REACT_APP_API_BASE_URL
              value: "http://gemini-voice-backend"