apiVersion: v1
kind: Service
metadata:
  name: gemini-voice-frontend
  namespace: gemini-voice-chat
spec:
  selector:
    app: gemini-voice-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer